version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5435/hotel-management

  db:
    image: postgres:15
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_DB: hotel-management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: