name: Deploy

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["CI"]
    branches: [ main ]
    types: [completed]

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'push'
    environment: staging

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: hotel-data-merge:staging-${{ github.sha }}
        outputs: type=docker,dest=/tmp/image.tar

    - name: Deploy notification
      run: |
        echo "🚀 Staging deployment would happen here"
        echo "Image: hotel-data-merge:staging-${{ github.sha }}"
        echo "Environment: staging"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: success()
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Production deployment
      run: |
        echo "🚀 Production deployment would happen here"
        echo "This step requires manual approval via GitHub environments"
        echo "Image: hotel-data-merge:staging-${{ github.sha }}"
        echo "Environment: production"